python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/gops_calculation/squeezenet_5.ini
