python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/pruned_acc/squeezenet_2.ini
