# python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_1.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_2.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_3.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_4.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_5.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_6.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_7.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_8.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_9.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_10.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_11.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_12.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_13.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_14.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_15.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_16.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_17.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_18.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_19.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_20.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_21.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_22.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_23.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_24.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_25.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_26.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_27.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_28.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_29.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_30.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_31.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_32.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_33.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_34.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_35.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_36.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_37.ini
