python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/alexnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
