python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_1.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_2.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_3.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_4.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_5.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_6.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_7.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_8.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_9.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_10.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_11.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_12.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_13.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_14.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_15.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_16.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_17.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/resnet_18.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_1.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_2.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_3.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_4.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_5.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_6.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_7.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_8.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_9.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_10.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_11.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_12.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_13.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_14.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_15.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_16.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_17.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/mobilenetv2_18.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_1.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_2.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_3.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_4.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_5.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_6.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_7.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_8.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_9.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_10.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_11.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_12.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_13.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_14.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_15.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_16.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_17.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/alexnet_18.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_0.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_1.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_2.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_3.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_4.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_5.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_6.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_7.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_8.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_9.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_10.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_11.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_12.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_13.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_14.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_15.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_16.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_17.ini
python main.py --config-file /home/nvidia/ar4414/pytorch_training/src/ar4414/pruning/configs/tx2_timing/squeezenet_18.ini
