python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/resnet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_19.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_20.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_21.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_22.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_23.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_24.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_25.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_26.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_27.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_28.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_29.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_30.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_31.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_32.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_33.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_34.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_35.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_36.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/l1_prune/squeezenet_37.ini
