python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/alexnet_18.ini
