python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/mobilenetv2_18.ini
