python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/squeezenet_18.ini
