python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_0.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_1.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_2.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_3.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_4.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_5.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_6.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_7.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_8.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_9.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_10.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_11.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_12.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_13.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_14.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_15.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_16.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_17.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_18.ini
python main.py --config-file /home/ar4414/pytorch_training/src/ar4414/pruning/configs/data_agnostic_l1_prune/resnet_18.ini
